language: node_js
sudo: false
node_js:
- '8'
cache: yarn
before_install:
  # AWS CLI
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_deploy:
  - yarn run build
deploy:
  # S3 deployment with fine-grained cache control not yet supported by TravisCI
  # https://github.com/travis-ci/dpl/issues/486
  provider: script
  script:
    # Sync built files. Cache non-HTML files.
    - aws s3 sync public/ s3://dev-tab-website --region us-west-2 --exclude "*" --include "*.html" --cache-control no-cache --metadata-directive REPLACE
    - aws s3 sync public/ s3://dev-tab-website --region us-west-2 --include "*" --exclude "*.html" --cache-control max-age=31536000 --metadata-directive REPLACE
  skip_cleanup: true
env:
  global:
  - secure: DziTcDvBh3LRq91xAnoSgxA/NiOUnRgDco3hUIAGInRQjKbPqOlIAZN4hPAOErVVuMCvDgGtrgtRGouufdTjhjgG7fklxpLQJhsfuDhTN72wvgoC8Y/vHPZcRGVlu7iz51mZP2bDXUpGkSBwkZbsmoQTONT1JKqRi4fKLe5V1i6quTdpnxFxb35QODCRrvWnd8zRb+3toWHk3p//Xmi04a+ZQfyYPtTW2Fow/iH/0PhFMmKoXDy+X+pDo8Xmi36+HNypb4ZmboY1CZDbwaRxIqa7S5CEXmNX/cql5kMRLx9bYrK/Vs/zHp5mtmm7hQVUH+3vHXwzWMC7TMX4s/tLh7BcOaF3LWEewks38nzZBshG5GYotUDnnSsTW1jsPyUTOp3YioAeYfvkvA3oypNvr2u1l5gkkA1pUSEOEcB5iJGIfMBbVbAfrKgt41xpFhXMw6YU98ycZQM13UvNkaBcbzgmu+hQKTp1x1gJkTtmwL4xlY6z0ZTgPP9ZYXOEmddQ/AFzXtpsu6MHG/4DqhwKpZLbrGoikgyQ4qPpeTqwB4QoVZVTpSFclMTAXwwsF7UutyCsQfhSF9COctZ6pWY6olpsXFrEdW0dRsD1lKh5gVT0d5uE7uVpFr/jyugr6scfGx6WjP55VqbXYF43IijM/VJXKwUdLf93a/Qcye8sdog=
  - secure: nsYTijPccDgzIPU4jQhV3nj8EjjipcpxbUzfwIiq6rRxW0HXUb8ad1K49q7YWqiWzmQLj2ZSxJ/xatzt672HRT8ZYqfBTNN69ZgCeAoNCx2PQTuA02wxhtMtRmgeN52Fbt0EAgNIg/AD/VHO9WjSZyW47dFL6lkGCeYEW3Znd/1A+8phGefV2tcQF+txczVU9Y2lcLq0aUN/86M+4nkBTYgYzYbCJK6Apzso3+GDREYfRW1sw5kKBD/l9OqxdX5IBM30owamjxYu6JxAdpReQC8WBDJ0aGOaqugWJjsI6tsa7l7Ya3MkbKn7gl2yUB594szzMwARAzZHjCij1Wjy6Sw+jthxYftC3P+TE2thqMeP7FlFq+CC4AYa0YkVdDvOMn/WO3EHpuBOqWHLDChv2SXMdgF8cs/DhGCOf4qV0g0MPmZ1co089PBlsQPU8yHwlXsP6kA51CIne/vMR7aElxnpP7eLAMw9edfCi8RvjTIjBoyZP6loZC2DRFxrGYpmacpT4AXFslTtMKIXEFlbnjz5h6RChAkgk6+cKM2/30eaRDXwMId7DkzrqnpLGKl8i/8HMc0j7adZkIf6u9u4U0EYIl9aBVZ/ozURZwURG/oli/y/w27Zn9tDVFky3Rq5PwFrOiUH5/Lg0+KQpfrkjWL5i+95f9uQLLKcmRGv4RU=
