language: node_js
sudo: false
node_js:
- '8'
cache: yarn
before_deploy:
  - yarn run build
deploy:
  provider: s3
  access_key_id:
    secure: "wvdNxTbHF0UEcZjXz0xwxpNJzyHTYNDUZzX+zz+5Go/1L4inLHNxtnTdmLu79PIqFykmkaKB4bdbGqyxBOpMggYeYzFn9PPmdNexTOlj5vNVHxnLQyAi3lPScDsxhennPdd1BVbIE4SGCxwF40qajXPurAWocMqHXpF5uUs+3juxm61FJSjwV4Qv+oodizmePtBNVAw6cR+IAZlu34+0z3trwnIXj0dRHIzpC3ryCiUZv8WiTeAl9COuyFdmvrJYouVrIIErawrro1Vde/J1M1swgmHdA6LroYf+zIOKmn9itj0GbnMHkul0djaOncVJU9IM+wCT+T8FByn9elT5Iwl4JuaMVplR/R9R3OmwrAU97Onsh/Vs8gGB8oiRpQ/WOow1q9BtdKRz3Me2EzCglgXtaowNI20epP7KemSdjn4ISR1b9aX/tFhOrQ0yPwsgIS1XsIot5A3cuyWObQgwRWfPnh75MchikE8gVvZW4ubILPaUraGVtCfxeinK/nha97xU7ifC8xZNOwEqn/wS2tBShQYzaVAh/2iiIYmJE4V6joET1k3Pg766tSNrn3jO3B9nhFDFlTevKASJ2+w2RyL5VVbmJpHy71169DZb7OUPanyucvmiz0+jVdMWSjGNsaeLdETTQPceBjJcApCzDWJbq2sBFdnCYSD6CU6BytI="
  secret_access_key:
    secure: "S1lDdSzBNzgKQjatj/bNScfN7bR6QR4RkQa+qfVxUdetYGN3IVpanyrGFpabZ+861Zodkmf1wbC8fGujx+U+o2sQYOw6YMlb3Bro7B6Do+gbx4PHnN10lCDgp2iicIc5WjOdGSy0JgJg/b7z1PX1LXMm4P8Hjdsk3mH1obAGHSSbkmZAbJ+NH7dL+0hxxOffY+79IzuU34x5Jn4dq0N7YkCY4DYyhPElVHkBDyMgJF9YZnXv1IDus8teMMWktLC34In/VhhwvgZ3jIWaBa24XzSjHHRl5uQ/82JChKtsqqoXFFkE39tjuqStUrE2jz9E8p4z0FezJ0mloXtz/SH7prGUs0FEsiQOxXTjxuz4EBW6T+4+JgHBuTMbBOajZn5U1pL/4a7VzUOMXvUbmwqcexvTEivQTYh8Cv3lcznyavVUjMHvBRMs/+5zP1JYbqwcWZyq6CUI4dYO/yg6SYX7jcHEUckUyX8GA7Q9a5jFUr8dHRt5Jv/bRjN31j05XfDkByB3/MFFnJ8sWxouR6i2YPmoPX0PcPCWwPr4QDHfcHue9/91OJlWzxask2rQ8EIwh6oVRIt/J+Oy8g8D/oZR1vGOFG96kgg+7VM94B29+v8rCfH9dyjpnA8bhtkQIoa0dNaoJMtyT0GP9i6GdSCbTwE6A4rOCSFP0qOrrZ1YbPw="
  bucket: dev-tab-website
  local_dir: public
  skip_cleanup: true
  region: us-west-2
